apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: vipul05/azure_learning
        image: quay.io/vipul05/azure_learning:latest
        ports:
        - containerPort: 80